FROM mcr.microsoft.com/playwright:v1.57.0@sha256:3bed4b1a12f2338642f3d8cba28e291deef3c66bd4a964bbeb3e57bbff511dbd

WORKDIR /app

# required by the e2e test code
RUN npm install "@playwright/test@^1.57.0" "dotenv@^16.3.1" "@grafana/plugin-e2e" "@grafana/i18n@^12.3.0"

ENV TZ=Europe/Madrid

ENTRYPOINT ["npx", "playwright", "test", "-c", "e2e/config/playwright.config.ci.ts"]
