name: CI

on:
  workflow_dispatch:
    inputs:
      skip-grafana-dev-image:
        description: Skip the grafana dev image e2e test
        required: false
        type: boolean
        default: false
  pull_request:
    branches:
      - main

permissions:
  contents: "read"
  id-token: "write"

jobs:
  CI:
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@ci-cd-workflows/v5.0.0
    with:
      run-playwright: false
      run-playwright-docker: true
      # TEMP until the Docker Hub issue is fixed (2025-07-09)
      run-playwright-with-skip-grafana-dev-image: true
      # run-playwright-with-skip-grafana-dev-image: ${{ inputs.skip-grafana-dev-image || false }}
      upload-playwright-artifacts: true
      playwright-report-path: e2e/test-reports/
      playwright-docker-compose-file: docker-compose.yaml
      playwright-grafana-url: http://localhost:3001
